name: 'Collect Files'
description: 'Collects files based on a glob pattern and copies them to a specified target directory.'
author: 'Ralph Schuler'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'fheart'
  color: 'red'

# Define your inputs here.
inputs:
  pattern:
    description: 'Glob pattern to match files against'
    required: true
  output_directory:
    description: 'The target directory where files are copied'
    required: false

# Define your outputs here.
outputs:
  output_directory:
    description: 'The target directory where files are copied'

runs:
  using: node20
  main: dist/index.js
